services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: llm-evals-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn main:app --host
    env_file:
      - ./.env
    network:
    - app


networks:
  app:
    external: true